version: 2
updates:
  - package-ecosystem: terraform
    directory: /terraform/environments/assessment/foundation
    schedule: {interval: weekly}
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: weekly}
